name: Python CI

# main 브랜치에 push 또는 pull_request 이벤트가 발생했을 때 워크플로우를 실행합니다.
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1단계: 레포지토리 코드 체크아웃
      - name: Check out code
        uses: actions/checkout@v4

      # 2단계: 파이썬 환경 설정
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      # 3단계: 의존성 설치
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4단계: 테스트 실행
      - name: Run tests
        run: pytest
